# Generated by Django 4.1.5 on 2023-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
