# Generated by Django 4.1.5 on 2023-04-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_stripe_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
