# Generated by Django 4.1.5 on 2023-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0009_remove_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishes',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
