# Generated by Django 4.1.5 on 2023-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0011_remove_user_wishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
