# Generated by Django 4.1.5 on 2023-04-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_alter_comment_commentowner_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
