# Generated by Django 4.1.5 on 2023-04-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_comment_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentOwner',
            new_name='comment_owner',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='productReviewed',
            new_name='product_reviewed',
        ),
    ]
