# Generated by Django 4.1.5 on 2023-04-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_remove_wish_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='productWished',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='wishOwner',
        ),
    ]
