# Generated by Django 4.1.5 on 2023-04-19 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_about_alter_product_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishes', '0003_remove_wish_productwished_remove_wish_wishowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='productWished',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wished', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='wishOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
