# Generated by Django 4.1.5 on 2023-04-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0005_alter_wish_productwished'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='text',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
