# Generated by Django 4.1.5 on 2023-04-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_about_alter_product_description_and_more'),
        ('wishes', '0007_remove_wish_productwished'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='productWished',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='wished', to='products.product'),
            preserve_default=False,
        ),
    ]
