# Generated by Django 4.1.5 on 2023-04-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0009_remove_wish_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='productWished',
            new_name='product_wished',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='wishOwner',
            new_name='wish_owner',
        ),
    ]
