# Generated by Django 4.1.5 on 2023-04-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.TextField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
