# Generated by Django 4.1.5 on 2023-04-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='basketOwner',
            new_name='basket_owner',
        ),
        migrations.RenameField(
            model_name='basket',
            old_name='productAddedToBasket',
            new_name='product_added_to_basket',
        ),
    ]
